### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ElijahTobs** [PhillipUg/not-todo-list#1]
Well done @SafaErden and @PhillipUg . You two have done a great job but there are still some things you need to fix:
- When there are 2 or more todos and you delete one of them, you're unable to delete the other.
- Beside the pen icon of a todo is another icon that is supposed to turn green when clicked on but it's not functioning.

Fix these issues and you're good to go...
Happy coding..

**Comment by PhillipUg** [comment]
Thanks for the tips @ElijahTobs. We will definately implement the suggested changes. 👍🏿
